# Generated by Django 5.0.3 on 2024-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0013_remove_perfil_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
